title: Teagan Collyer Portfolio

logo: assets/me_edited.jpg

description: Just some random description

show_downloads: true

theme: jekyll-theme-minima #jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

email: portfolio@snowyjaguar.xyz
